name: Tests

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  pull_request:
    branches-ignore: []
  schedule:
    - cron: '0 0 13 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.9, '3.10', '3.11', '3.12']
      fail-fast: false


    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: conda/mamba
      uses: mamba-org/setup-micromamba@v1
      with:
          cache-downloads: true
          #environment-file: false
          environment-name: installation
          channels:
            conda-forge,bioconda,defaults
          create-args: >-
            python=${{ matrix.python }}
            kraken2
            shustring
            samtools
            mosdepth
            snpeff
            bwa
            shustring
            cd-hit
          condarc: |
            channels:
              - conda-forge
              - bioconda
            channel_priority: strict

    - name: install package itself
      shell: bash -l {0}
      run: |
        pip install poetry
        poetry install --with dev,pipelines
        #pip install .[testing]
        pip install kaleido  # required by plotly but sowehow not installed

    - name: testing
      shell: bash -l {0}
      run: |
        poetry run pytest --cov-report term-missing --cov=sequana

    - name: coveralls
      shell: bash -l {0}
      run: |
        pip install coveralls
        coveralls --service=github
      env:
          GITHUB_TOKEN: ${{ github.token }}
